version: "3.9"
services:
  redis:
    image: "redis:latest"
    container_name: "redis-1"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      sh -c "apt-get update && 
                   apt-get install -y zsh procps && 
            redis-server"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
